export const IPC = {
  COPY_TO_CLIPBOARD: 'COPY_TO_CLIPBOARD',
  GET_CLIPBOARD_CONTENT: 'GET_CLIPBOARD_CONTENT',
  MINIMIZE_WINDOW: 'MINIMIZE_WINDOW',
  MAXIMIZE_WINDOW: 'MAXIMIZE_WINDOW',
  CLOSE_WINDOW: 'CLOSE_WINDOW'
} as const; 